#:schema node_modules/wrangler/config-schema.json

name = "arqlopes-site"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Static assets
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# R2 bucket for content and images
[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "arqlopes-assets"

[vars]
NEXT_PUBLIC_R2_URL = "https://pub-9def9de695584c4c8300c62ce8af1bbd.r2.dev"
